import React from 'react';
const valueMM=value=>Number(value).toFixed(1)+'mm';
export default function GableJobFront({inputs,geometry:g,model,job,details,customerName,onChange,onSave,message}){
 const edit=(key,type='text')=><input aria-label={key.replace(/_/g,' ')} type={type} value={details[key]||''} onChange={e=>onChange({...details,[key]:e.target.value})}/>;
 const address=details.delivery_address_json||{},editAddress=(key,value)=>onChange({...details,delivery_address_json:{...address,[key]:value}});
 const headers=[['Job Number','Customer Name','Customer Reference','Delivery Date'],['Delivery / Install','Style','Roof Pitch','Frame Thickness'],['Tile Type','Tile Colour','Fascia / Soffit Colour','Soffit / Overhang'],['Gutters','Downpipes','Internal Dimensions','Roof Weight']];
 const values=[[edit('job_number'),job?.customer_name||customerName||inputs.customerName||'—',inputs.customerReference||'—',edit('requested_delivery_date','date')],[<select aria-label="Delivery type" value={address.deliveryType||'Delivery'} onChange={e=>editAddress('deliveryType',e.target.value)}><option>Delivery</option><option>Install</option><option>Collection</option></select>,'Gable',Number(g.pitchDeg).toFixed(1)+'°',valueMM(g.frameMM)],[inputs.tileProductId==='liteSlate'?'LiteSlate':inputs.tileProductId==='metrotileShingle'?'Metrotile Shingle':'Britmet Shingle',inputs.tileColour||'—',inputs.fasciaColour||'White',`Sides ${g.leftSoffitMM}/${g.rightSoffitMM}mm · front ${g.frontOverhangMM}mm`],[`${inputs.gutterProfile||'square'} · ${inputs.gutterColour||'White'}`,'Two round downpipes',`${g.widthMM} × ${g.projectionMM}mm`,Number(model.installedWeightKg).toFixed(1)+'kg known']];
 const extras=Object.values(model.sections).flatMap(s=>s.lines).filter(row=>row.isAddedItem&&row.qty>0&&row.usage!=='factory').map(row=>`${Number(row.qty.toFixed(3))} ${row.units} ${row.label}`);
 return <div className="gj-front"><table className="gj-grid"><tbody>{headers.map((row,n)=><React.Fragment key={n}><tr>{row.map(label=><th key={label}>{label}</th>)}</tr><tr>{values[n].map((value,k)=><td key={k}>{value}</td>)}</tr></React.Fragment>)}</tbody></table>
 <div className="gj-delivery"><h3>Delivery Address, Special Instructions, Extras</h3><label>Delivery address<textarea aria-label="Delivery address" value={address.deliveryAddress||inputs.deliveryPostcode||''} onChange={e=>editAddress('deliveryAddress',e.target.value)}/></label><div className="gj-contact"><label>Contact name<input aria-label="Contact name" value={address.contactName||''} onChange={e=>editAddress('contactName',e.target.value)}/></label><label>Contact phone<input aria-label="Contact phone" value={address.contactPhone||''} onChange={e=>editAddress('contactPhone',e.target.value)}/></label></div><label>Special instructions<textarea className="gj-notes" aria-label="Special instructions" value={details.order_notes||''} onChange={e=>onChange({...details,order_notes:e.target.value})}/></label><p><b>Summary extras:</b> {extras.length?extras.join(' · '):'None added'}</p></div>
 <p className="gj-allowance"><b>Factory:</b> manufacturing projection {valueMM(g.manufacturingProjectionMM)} includes the 5mm front soffit clearance. Do not add again. Requested external projection {valueMM(g.externalProjectionMM)}. Roof weight includes plasterboard once; supply only when added.</p>
 <div className="gj-signoff">Manufactured by: ____________________ Date: __________<br/><br/>Checked / authorised by: ____________________ Date: __________</div>
 <div className="gm-controls"><button type="button" onClick={onSave}>{job?'Save job details':'Save draft book details'}</button><p role="status">{message}</p>{!job&&<p>Draft book. Convert the saved quotation to a job to record its job number and delivery details in Jobs.</p>}</div>
 <style>{`.gj-grid{table-layout:fixed}.gj-grid th{background:#f1f5f9;font-size:13px}.gj-grid td{font-size:14px;overflow-wrap:anywhere;height:43px}.gj-grid input,.gj-grid select{box-sizing:border-box;font:inherit;padding:4px!important;margin:0;width:100%!important;border:1px solid #cbd5e1}.gj-delivery{border:1px solid #94a3b8;padding:12px}.gj-delivery h3{font-size:17px;margin:0 0 12px}.gj-delivery label{font-size:13px;font-weight:bold;margin:8px 0!important}.gj-delivery textarea{display:block;box-sizing:border-box;width:100%;height:90px;margin-top:5px;padding:8px;font:14px Arial;border:1px solid #cbd5e1;resize:vertical}.gj-delivery .gj-notes{height:90px}.gj-contact{display:grid;grid-template-columns:1fr 1fr;gap:12px}.gj-contact input{box-sizing:border-box;width:100%!important;padding:6px!important;font:14px Arial}.gj-allowance{font-size:12px!important}.gj-signoff{font-size:14px;border-top:1px solid #94a3b8;margin-top:15px;padding-top:15px}@media print{.gj-front input,.gj-front select,.gj-front textarea{border:0!important;appearance:none}.gj-delivery textarea{resize:none}}`}</style>
 </div>;
}
