import React,{useState,useEffect} from 'react';
import {Link,Navigate} from 'react-router-dom';
import {isAdminUser} from '../../lib/userRole';
import {getMaterials} from '../../lib/materials';
import {getQuoteById,updateQuote} from '../../lib/quotes';
import {isGableQuote} from '../../lib/Calculations/gableQuotation';
import {buildGableSummaryMaterialsModel} from '../../lib/Calculations/gableSummaryMaterialsModel';
import {buildGableManufactureSchedule} from '../../lib/Manufacturing/gableManufactureSchedule';
import SummaryIdiotList from '../../components/SummaryIdiotList';
import GableNavigation from './GableNavigation';
import GableJobFront from './GableJobFront';
import {getCustomers} from '../../lib/customers';
const mm=v=>Number(v).toFixed(1);
const read=()=>{try{return JSON.parse(localStorage.getItem('gableDesignPreviewInputs')||'{}');}catch{return {};}};
function Table({head,rows}) {return <table><thead><tr>{head.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,n)=><tr key={n}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table>;}
export function Shape({points,title}) {
 const xs=points.map(p=>p.xMM),ys=points.map(p=>p.yMM),minX=Math.min(...xs),maxY=Math.max(...ys),scale=Math.min(880/(Math.max(...xs)-minX||1),260/(maxY-Math.min(...ys)||1));
 return <svg viewBox="0 0 1000 350" role="img" aria-label={title}><text x="40" y="30" fontSize="25">{title}</text><polygon points={points.map(p=>`${60+(p.xMM-minX)*scale},${65+(maxY-p.yMM)*scale}`).join(' ')} fill="#e2e8f0" stroke="#111827" strokeWidth="3" />
 </svg>;
}
export function GablePlan({schedule:s}) {
 const g=s.geometry,W=650,L=800,left=130,top=85,px=x=>left+x/g.externalWidthMM*W,py=y=>top+y/g.manufacturingProjectionMM*L;
 const frameX=g.feet[0].hfcMM;
 return <svg viewBox="0 0 1000 1120" role="img" aria-label="Gable truss setting-out plan">
 <defs><marker id="gable-dim-arrow" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#334155" /></marker></defs>
 <rect x={left} y={top} width={W} height={L} fill="#f1f5f9" stroke="black" strokeWidth="3" />
  <rect x={px(frameX)} y={top} width={g.widthMM/g.externalWidthMM*W} height={g.projectionMM/g.manufacturingProjectionMM*L} fill="none" stroke="#64748b" strokeDasharray="9 5" />
 <line x1={px(frameX+g.widthMM/2)} x2={px(frameX+g.widthMM/2)} y1={top} y2={top+L} stroke="#64748b" strokeDasharray="10 6" />
 <text x="130" y="40" fontSize="26">House wall — all positions measured from here</text>
 {s.trusses.map((t,n)=><g key={t.id}><line x1={left} x2={left+W} y1={py(t.centreMM)} y2={py(t.centreMM)} stroke="#92400e" strokeWidth="5" /><text x="25" y={py(t.centreMM)+8} fontSize="25">{t.id}</text><text x="800" y={py(t.centreMM)+8} fontSize="25">{n===0?'Wall':Math.round(t.centreMM)+'mm'}</text>{n>0&&<text x="150" y={py((t.centreMM+s.trusses[n-1].centreMM)/2)+8} fontSize="23" fill="#334155">{mm(g.layout.gapsMM[n-1])} centres</text>}</g>)}
 <line x1={px(frameX)} x2={px(frameX+g.widthMM)} y1="935" y2="935" stroke="#334155" markerStart="url(#gable-dim-arrow)" markerEnd="url(#gable-dim-arrow)" /><text x={left+W/2} y="925" textAnchor="middle" fontSize="24">Internal width {mm(g.widthMM)}mm</text>
 <line x1={left} x2={left+W} y1="986" y2="986" stroke="#334155" markerStart="url(#gable-dim-arrow)" markerEnd="url(#gable-dim-arrow)" />
 <text x="130" y="976" fontSize="25">External width {mm(g.externalWidthMM)}mm</text><text x="130" y="1018" fontSize="23">Internal projection {mm(g.projectionMM)}mm (dashed frame)</text><text x="130" y="1053" fontSize="25">Manufacturing projection {mm(g.manufacturingProjectionMM)}mm</text><text x="130" y="1080" fontSize="23">RB1 left · RB2 right · ridge centred on internal frames</text>
 </svg>;
}
export default function GableManufacture(){
 const [inputs]=useState(read),[materials]=useState(getMaterials),[job,setJob]=useState(null),[details,setDetails]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('gableBookDetails')||'{}');return saved.reference===inputs.customerReference&&Number(saved.widthMM)===Number(inputs.widthMM)&&Number(saved.projMM)===Number(inputs.projMM)?saved.details||{}:{};}catch{return {};}}),[message,setMessage]=useState(''),[customerName,setCustomerName]=useState('');
 useEffect(()=>{let alive=true;getCustomers().then(rows=>{if(alive)setCustomerName((rows||[]).find(c=>c.id===inputs.selectedCustomerId)?.name||(inputs.selectedCustomerId==='retail'?'Retail':'Customer unavailable'));}).catch(()=>{if(alive)setCustomerName('—');});const id=localStorage.getItem('active_gable_job_id');if(id)getQuoteById(id).then(record=>{if(alive&&isGableQuote(record)&&record.inputs_json?.customerReference===inputs.customerReference&&Number(record.inputs_json?.widthMM)===Number(inputs.widthMM)&&Number(record.inputs_json?.projMM)===Number(inputs.projMM)){setJob(record);setDetails({job_number:record.job_number||'',requested_delivery_date:record.requested_delivery_date||'',order_notes:record.order_notes||'',delivery_address_json:record.delivery_address_json||{}});}}).catch(()=>{if(alive)setMessage('Job details could not be loaded.');});return()=>{alive=false;};},[inputs]);
 if(!isAdminUser())return <Navigate to="/quote/gable" replace />;
 const model=buildGableSummaryMaterialsModel({inputs,materials}),s=buildGableManufactureSchedule(model,materials);
 if(!s.valid)return <main><p>{s.errors.join(' ')}</p><Link to="/quote/gable">Return to Design/Options</Link></main>;
 const g=s.geometry,j=g.truss,i=s.insulation,plastics=model.audits.plastics;
 const page=(title,content)=><section key={title} className="gm-page"><h2>{title}</h2><div className="gm-ref">{job?.customer_name||customerName||'—'} · {inputs.customerReference||'Gable'} · {inputs.widthMM} × {inputs.projMM}mm · {mm(g.pitchDeg)}° · {inputs.fasciaColour||'White'} fascia · {inputs.gutterColour||'White'} gutter · {mm(model.installedWeightKg)}kg</div>{content}</section>;
 const save=async()=>{if(!job){localStorage.setItem('gableBookDetails',JSON.stringify({reference:inputs.customerReference,widthMM:inputs.widthMM,projMM:inputs.projMM,details}));setMessage('Draft book details saved on this device.');return;}try{const result=await updateQuote(job.id,details);setMessage(result?'Job details saved.':'Job details could not be saved.');}catch{setMessage('Job details could not be saved.');}};
 return <main className="gm-book"><GableNavigation/><div className="gm-controls"><Link to="/quote/gable/summary">Summary</Link> · <Link to="/quote/gable">Design/Options</Link> <button onClick={()=>window.print()}>Print manufacture book</button></div>
 {page('Manufacture Book',<GableJobFront inputs={inputs} geometry={g} model={model} job={job} details={details} customerName={customerName} onChange={setDetails} onSave={save} message={message}/>)}
 {page('Roof plan',<GablePlan schedule={s}/>)}
 {page('Truss members',<>{s.members.map(f=><div key={f.side}><Shape points={f.points} title={`${f.side} member — ${s.trusses.length} required`}/><Table head={['External slope','Internal slope','HFC','VFC','Apex cut']} rows={[[mm(f.externalSlopeMM),mm(f.internalSlopeMM),mm(f.hfcMM),mm(f.vfcMM),mm(g.pitchDeg)+'° off square']]}/></div>)}<p>220mm joists; 45mm flanges. Plumb apex joint with no spar-hook deduction. Rear face has 9mm faceplate and wall packers. Intermediate trusses have PIR cradles on both faces; end trusses on inward faces only.</p></>)}
 {page('Truss joint components',<><Shape points={j.chevron.points} title={`18mm chevrons — ${s.componentCounts.chevrons} required`}/><p>Longest arm 300mm · perpendicular strip width 143mm.</p><Shape points={j.gusset.points} title={`9mm gussets — ${s.componentCounts.gussets} joint faces`}/><Table head={['Bottom width','Vertical sides','Overall height','Sloping edges']} rows={[[mm(j.gusset.widthMM),mm(j.gusset.sideHeightMM),mm(j.gusset.blankHeightMM),mm(j.gusset.slopeEdgeMM)]]}/></>)}
 {page('Truss closure',<><Shape points={j.closure.points} title={`Assembled rafter-offcut closures — ${s.componentCounts.closures} required`}/><p>Bottom {mm(j.closure.cutLengthMM)}mm · top {mm(j.closure.shortEdgeMM)}mm · depth 45mm · ends {mm(j.closure.endCutOffSquareDeg)}° off square. Glue and fix using the established workshop method.</p></>)}
 {page('Front truss face',<><Shape points={s.frontFace.points} title="Full outer 9mm face — front truss only"/><p>Continue the face over both members and the gusset outline, leaving the A-frame opening clear. The outer gusset is included in this single layer, not covered with a second duplicate layer.</p><p>Front fascia: 300mm stock on the slopes; one central box-end blank, cut to fit the gusset. Exact box-end outline remains a workshop detail.</p></>)}
 {s.ringBeamGroups.map(group=>page(`Ring-beam ${group.manufactureRefs.join(' / ')}`,<><p>{group.quantity} required · both ends square · dimensions in mm.</p><Table head={['Component','Length','Width / height','Quantity']} rows={[["9mm ply base",mm(group.cuts.lengthMM),mm(group.cuts.baseWidthMM),group.quantity],["30×95 PSE",mm(group.cuts.lengthMM),95,group.quantity],["25×50 external fixing lath",mm(group.cuts.lengthMM),50,group.quantity]]}/><svg viewBox="0 0 1000 240" role="img" aria-label="Ring-beam bay setting-out"><rect x="50" y="60" width="900" height="75" fill="#e2e8f0" stroke="black"/>{s.bays.map(b=><g key={b.id}><rect x={50+b.startMM/g.manufacturingProjectionMM*900} y="60" width={(b.endMM-b.startMM)/g.manufacturingProjectionMM*900} height="75" fill="#bfdbfe" stroke="#334155"/><text x={50+(b.startMM+b.endMM)/2/g.manufacturingProjectionMM*900} y="102" textAnchor="middle" fontSize="20">{group.quantity===2?b.id+'/'+b.pairedId:group.sides[0]==='right'?b.pairedId:b.id}</text></g>)}<text x="50" y="190" fontSize="24">House wall → front · member centres follow roof plan</text></svg><Table head={['Bay labels','9mm upstand width','Upstand height','50mm PIR faces']} rows={s.bays.map(b=>[group.quantity===2?`${b.id}/${b.pairedId}`:group.sides[0]==='right'?b.pairedId:b.id,mm(b.upstandWidthMM),195,`${group.quantity*2} × ${mm(b.upstandWidthMM)} × 185`])}/><p>48mm fitting slots; upstand finishing laths match each bay width. Square-ended base and timber runs share the full manufacturing projection.</p></>))}
 {page('Insulation and internal laths',<><Table head={['Cut / requirement','Dimension','Quantity']} rows={[["50mm rebated cradle strips",`${mm(i.cradle.runMM)} × 140mm`,i.cradle.facesPerSide*2],["100mm PIR slope run to apex",mm(i.slab.runMM)+'mm','Two per bay']]}/><Table head={['Between trusses','100mm PIR clear width']} rows={s.bays.map((b,n)=>[`T${n+1} / T${n+2}`,mm(b.slabWidthMM)])}/><p>50mm cradle ends at the gusset; 100mm slabs continue to the apex with chamfered meeting edges. Seal joints with expanding foam.</p><p>Internal laths: {model.audits.laths.internal.rows.length} runs × {mm(g.manufacturingProjectionMM)}mm. Lower laths sit at the foot-cut / ring-beam junction. Ceiling flat {mm(i.ceiling.flatWidthMM)}mm.</p><p>SuperQuilt and plasterboard installed coverage: {i.ceiling.areaM2.toFixed(3)}m², stopping at the inside front frame. Plasterboard is not supplied unless added in Summary.</p><p>Tile cutting and detailed lath cutting schedules will be added separately.</p></>)}
 {page('Fascia and soffit preparation',<><Table head={['Run','Length mm','Fascia stock','External cut height','Soffit width']} rows={plastics.sideRows.map(r=>[r.side,mm(r.runM*1000),r.widthMM+'mm',mm(r.fasciaCut.externalCutHeightMM??r.fasciaCut.finishedExternalHeightMM??0),mm(r.soffitGeometryMM)])}/><p>Front slopes to gusset: {plastics.frontRows.map(r=>mm(r.runM*1000)+'mm').join(' / ')}. Front soffit width {mm(g.frontOverhangMM)}mm; flat section {mm(i.ceiling.flatWidthMM)}mm. Cut box end to fit, then join to sloping fascias.</p><p>Only side eaves are factory vented. Stock quantities and fittings follow the final checklist; compatible offcuts are shared.</p></>)}
 {page('Despatch checklist',<SummaryIdiotList model={model} materials={materials} checklist={s.checklist} inputs={{...inputs,quoteRef:inputs.customerReference,customerName:job?.customer_name||inputs.customerName,tileSystem:inputs.tileProductId,plasticsColor:inputs.fasciaColour,gutterColor:inputs.gutterColour}}/>)}
 <style>{`.gm-book{font-family:Arial,sans-serif;color:#111827}.gm-controls{margin:15px}.gm-page{box-sizing:border-box;width:194mm;min-height:275mm;margin:18px auto;padding:7mm;background:white;border:1px solid #cbd5e1;break-after:page}.gm-page:last-of-type{break-after:auto}.gm-page:first-of-type h2{text-align:center;font-size:28px}.gm-page h2{font-size:21px;margin:0 0 8px}.gm-ref{font-size:12px;margin-bottom:14px}.gm-page p{font-size:15px;line-height:1.45}.gm-page svg{display:block;width:100%;height:auto}.gm-page table{width:100%;border-collapse:collapse;margin:14px 0;font-size:15px}.gm-page th,.gm-page td{border:1px solid #94a3b8;padding:7px;text-align:left}.gm-page tr{break-inside:avoid}.gm-page label{display:block;margin:15px 0}.gm-page input{display:block;padding:8px;width:90%}.gm-page .sil-note{font-size:12px}.gm-page .sil-details{font-size:13px}.gm-page .sil-row{padding:5px 0}@media print{@page{size:A4;margin:6mm}body{margin:0}.gm-controls,.nav-strip{display:none!important}.gm-page{margin:0;border:0;padding:4mm;min-height:275mm;width:100%}button{display:none!important}input{border:0!important}}`}</style>
 </main>;
}
